name: Load Testing

on: workflow_dispatch

jobs:
  k6:
    name: k6 Load Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [ forward, blocking, nio ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Docker build
        run: ./gradlew service:bootBuildImage gateway-${{ matrix.type }}:bootBuildImage

      - run: docker pull loadimpact/k6

      - name: Docker compose up
        run: docker-compose up -d gateway-${{ matrix.type }}

      - name: Run k6
        run: docker run --network host -i -v "$PWD:/benchmark" loadimpact/k6 run --quiet -e TYPE=${{ matrix.type }} /benchmark/test.js
        working-directory: benchmark
